language: python
python:
  - "2.7"
  - "3.2"
  
env:
  - TOXENV=py27
# command to install dependencies
install:
  #- "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install tox"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - tox
